// Code generated by sqlc. DO NOT EDIT.

package pg

import ()

type Member struct {
	ID   int64
	Name string
	Age  int32
}

type Skill struct {
	ID       int64
	Name     string
	Descs    string
	MemberID int64
}
